spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1041912776083-8l621cn5hqpm2pu44v3fuuv7a97tgrhk.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
            client-name: Google
